dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4

env:
    - APP_ENV=testing

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'create database enso;'

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - chmod -R 777 storage
  - php artisan key:generate
  - php artisan migrate

script: vendor/bin/phpunit

after_success:
  - curl -s $DEPLOY_WEBHOOK

sudo: required
