sudo: required
dist: trusty
services:
  - docker
  - neo4j

env:
  - IMAGE=mysql:5.7
    NAME=mysql
    OMIT_FEATURES=RsaEncryption,CachingSha2Password,Tls12,UuidToBin
  - IMAGE=mysql:8.0
    NAME=mysql
    OMIT_FEATURES=None

before_install:
  - chmod +x .ci/docker-run.sh && .ci/docker-run.sh $IMAGE $NAME 3307 $OMIT_FEATURES
  - npm install
  - npm run dev

language: php

php:
  - 7.2

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - composer update --prefer-dist

script:
  #- phpunit --coverage-clover coverage.xml
  - phpunit

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  # minimal required coverage is set to 80+ %
  # - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/coveralls.phar
  # - php coveralls.phar --verbose


notifications:
email: false
