version: '3'

services:
  genealogy-server:
    build: ./provisioning
    image: modulargenealogy
    depends_on:
      - mysql
      - neo4j
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:de482b2b0fdbe5bb142462c07c5650a74e0daa31e501bc52448a2be10f384e6d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:31b8e90a349d1fce7621f5a5a08e4fc519b634f7d3feb09d53fac9b12aa4d991
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - genealogy-server

  neo4j:
    image: neo4j:latest@sha256:d550653aaf4f7cde07917992052bdde5b935fca9c7e5c8b98cf7dfe590fbda71
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
