version: '3'

services:
  genealogy-server:
    build: ./provisioning
    image: laravel-genealogy
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:81679f23e0ece3e50a7300050191272e5afbf5b66be9b60d2ee0e8b575b152e2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:1f9c00b4c95ef931afa097823d902e7602aebc3ec5532e907e066978075ca3e0
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - genealogy-server

   neo4j:
      image: neo4j:latest@sha256:b037bf59676cb8d4a1e105e33a6155ce09933e63ef1217730f1cba6ae1300dd2
      ports:
        - "7474:7474"
      volumes:
        - ./db/dbms:/data/dbms
      depends_on:
        - genealogy-server